<a href="https://colab.research.google.com/github/D-J-C-H/Talento_Tech/blob/main/explicacion_numerica_de_MLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# explicacion_numerica_de_MLP

Por:

Andrés Felipe Escallón Portilla
(21 y 24 - junio - 2024)

Referencias:

*Basic numerical examples (MLP and others):

https://www.linkedin.com/posts/tom-yeh_deeplearning-llms-generativeai-activity-7161408843111956480-ujq0/


- Perceptron:

https://www.linkedin.com/posts/jeremyclondon_deeplearning-neuralnetworks-ai-activity-7171891528448008192-nulK/?utm_source=share&utm_medium=member_android

- Video about MLP numerical operation:

https://www.linkedin.com/posts/annarahn_deeplearning-neuralnetworks-math-ugcPost-7171662948967411712-ZIEx?utm_source=share&utm_medium=member_android


*Other:

- https://www.linkedin.com/posts/jeremyclondon_deeplearning-neuralnetworks-ai-ugcPost-7174203548736319488-RM0S?utm_source=share&utm_medium=member_android


- https://alfanotv.com/raspberry-pi/como-multiplicar-matrices-en-numpy-multiply-matmul/



In [ ]:
import numpy as np

array_1 = np.array(     [ [1, 1], [-1,1] ]   )


W = np.array(     [ [1, 1], [-1,1] ]   )
print("\n W = \n", W)
#print()


array_2 = np.array (   [  [1, 5, 2],    [2, 4, 2] ]    )

X = np.array (   [  [1, 5, 2],    [2, 4, 2] ]    )
print("\n X = \n",X)
#print()

WX_1 = np.dot(W,X)
print("\n WX_1 = \n",WX_1)
#print()

WX_2 = np.matmul(W,X)
print("\n WX_2 = \n",WX_2)
#print()

#XW = np.matmul(X,W)
#print(XW)
#print()
# Lo anterior no funciona por lo siguiente:
#X_(2,3) por W_(2,2) = Resultado_(2,2)?
#porque el numero de columnas de X es diferente al numero de filas de W


 W = 
 [[ 1  1]
 [-1  1]]

 X = 
 [[1 5 2]
 [2 4 2]]

 WX_1 = 
 [[ 3  9  4]
 [ 1 -1  0]]

 WX_2 = 
 [[ 3  9  4]
 [ 1 -1  0]]



```
W_(2,2) por X_(2,3) = WX_(2,3)

W*x + b = Z ---> Activation = output

W_(3,4) por x_(4,5) = Z_(3,5)

Asumiendo que todos los biases son cero y que NO hay función de activación (es decir: se deja pasar la misma información)

```


In [ ]:
W = np.array([   [1,1,0,-1], [-1,1,2,-3], [-1,1,5,0]  ])
print(W)

print()

x = np.array([ [1,5,2,-1,0], [2,4,2,1,-1], [7,5,6,-1,1], [-8,0,4,-1,3] ])
print(x)
print()

b = np.zeros((3, 5)) # suponer todos los valores de los biases en cero
print(b)
print()

Z = np.matmul(W,x) + b
print(Z)

[[ 1  1  0 -1]
 [-1  1  2 -3]
 [-1  1  5  0]]

[[ 1  5  2 -1  0]
 [ 2  4  2  1 -1]
 [ 7  5  6 -1  1]
 [-8  0  4 -1  3]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[11.  9.  0.  1. -4.]
 [39.  9.  0.  3. -8.]
 [36. 24. 30. -3.  4.]]


# Explicación manual:

```
W =
[[ 1  1]
 [-1  1]]

x=
 [[1 5 2]
 [2 4 2]]

Entonces:

W*x + b:

b=zeros
W*x  + 0 = W*x = Z
[[ 3  9  4]
 [ 1 -1  0]]

Z-->relu-->A
A=
[[ 3  9  4]
 [ 1  0  0]]

===============
W*x =
[[ 3  9  4]
 [ 1 -1  0]]

+ b (b=ones)
W*x + b:
[[ 4  10  5]
 [ 2  0   1]]

W*x + b = Z
Z-->relu-->A

A=
[[ 4  10  5]
 [ 2  0   0]]

=========================

Comparar el resultado conocido (Supervisado)
Supongamos que el resultado conocido es:
Y_real=
[[ 4  10  5]
 [ 2  0   0]]
y sucedió que la red calculó y dio:
A=Y_estimado
[[ 4  10  5]
 [ 2  0   0]]

Error(Y_real-Y_estimada)=?
E=
[[ 0  0  0]
 [ 0  0   0]]

===============================================
O supongamos que el resultado conocido debe ser:
Y_real=
[[ -3  6  2]
 [ 0   5 -1]]
y sucedió que la red calculó y dio:

A=Y_estimado
[[ 4  10  5]
 [ 2  0   0]]

Error(Y_real-Y_estimada)=?
E=
[[ -7  -4  -3]
 [ -2  5   -1]]


```






# Operaciones correctas vs incorrectas:

## Si no se cumple lo dicho incialmente, entonces no se puede multiplicar matrices desde el procedimiento de algebra lineal:

## "*" y multiply son para multiplicar elemento a elemento matrices del mismo tamaño = num_filas x num_columnas

In [ ]:
#array_r_bad1 = array_1 * array_2
#print(array_r_bad1)

np.array([1,1])*np.array([1,1,1])

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [ ]:
print(np.array([2,4])*np.array([3,-5]))

[  6 -20]


In [ ]:
np.multiply(np.array([2,4]), np.array([3,-5]))

array([  6, -20])

In [ ]:
array_r_bad2 = array_2 * array_1
print(array_r_bad2)

In [ ]:
mult3 = np.multiply(array_1,array_2)
print(mult3)

# HOMEWORK:

# Ejemplo académico:

Definiendo funciones en python para calcular:

 W x + b = Z --> relu ---> y

In [ ]:
import numpy as np

def get_output_from_MLP_input(W,x,b,activation="linear"):
  #print("W = ",end='\n')
  #print(W)
  print(f"W = \n {W} \n")
  #print()

  print("x = ",end='\n')
  print(x)
  print("b = ",end='\n')
  print(b)
  # arguments:
  # W,x and b are arrays

  # operations
  # Z = W x  +  b
  #Z = np.matmul(W,x) + b
  Z = np.dot(W,x) + b

  print("Z = ",end='\n')
  print(Z)

  if activation=="linear":
    y = Z

#  if activation=="relu":
    # Ternary operator to define a relu function
    #y = Z if Z>=0 else 0
    #y = Z if Z>0 else 0
    #y = 0 if Z<0 else Z
    #y = 0 if Z<=0 else Z
#    y = np.array([0 if z<=0 else z for z in Z])

  elif activation =="relu":
     y = np.array([0 if z <= 0 else z for z in Z])

  #TO-DO:
  # Ver código de la tarea más abajo.

  elif activation =="sigmoid":
     y = 1 / (1 + np.exp(-Z))

  elif activation =="tanh":
     y = np.tanh(Z)

  elif activation =="leaky_relu":
     y = np.array([z if z > 0 else 0.01 * z for z in Z])

  elif activation == "maxout":
     # MaxOut necesita definir un grupo de W y b, aquí se asume que W y b están configurados correctamente para MaxOut
     k = 2  # número de unidades por grupo
     y = np.max([np.dot(W[i], x) + b[i] for i in range(k)], axis=0)

  #ELU (Exponential Linear Unit)
  elif activation == "elu":
     alpha = 1.0  # puedes ajustar el valor de alpha según sea necesario
     y = np.array([z if z >= 0 else alpha * (np.exp(z) - 1) for z in Z])

  elif activation == "arctan":
     y = np.arctan(Z)

  #Arctangente (ArcTang)
  else:
     raise ValueError(f"Unsupported activation function: {activation}")

  print("y = ", end='\n')
  print(y)

  return y


In [ ]:
# Testing (linear)

W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b)
y

W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[-1  3  5  3]


array([-1,  3,  5,  3])

In [ ]:
# Testing (linear)

W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b, activation="linear")
y

W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[-1  3  5  3]


array([-1,  3,  5,  3])

In [ ]:
# Testing (relu)

W = np.array([ [1,-1,1]  , [1,1,0] ,  [0,1,1] ,  [1,0,1]    ])
x = np.array([2, 1, 3])
b = np.array([-5, 0, 1, -2])

y = get_output_from_MLP_input(W,x,b,"relu")
y

W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[0 3 5 3]


array([0, 3, 5, 3])

In [ ]:
print("Activation: Sigmoid")
y = get_output_from_MLP_input(W,x,b,"sigmoid")
print()

print("Activation: Tanh")
output_tanh = get_output_from_MLP_input(W, x, b, activation="tanh")
print()

print("Activation: leaky_relu")
output_tanh = get_output_from_MLP_input(W, x, b, activation="leaky_relu")
print()

print("Activation: ELU")
output_elu = get_output_from_MLP_input(W, x, b, activation="elu")
print()

print("Activation: MaxOut")
output_maxout = get_output_from_MLP_input(W, x, b, activation="maxout")
print()

print("Activation: ArcTang")
output_arctan = get_output_from_MLP_input(W, x, b, activation="arctan")
print()

Activation: Sigmoid
W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[0.26894142 0.95257413 0.99330715 0.95257413]

Activation: Tanh
W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[-0.76159416  0.99505475  0.9999092   0.99505475]

Activation: leaky_relu
W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[-0.01  3.    5.    3.  ]

Activation: ELU
W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[-0.63212056  3.          5.          3.        ]

Activation: MaxOut
W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
3

Activation: ArcTang
W = 
 [[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]] 

x = 
[2 1 3]
b = 
[-5  0  1 -2]
Z = 
[-1  3  5  3]
y = 
[-0.78539816  1.24904577  1.

# Ojo: la multiplicacion entre matrices en general NO es conmutativa

AB=C en general es distinto de BA=D

(suponiendo que por las dimensiones se puedan operar)

Ejemplo: al intercambiar Wx con xW hay error

In [ ]:
y = get_output_from_MLP_input(x,W,b)

W = 
 [2 1 3] 

x = 
[[ 1 -1  1]
 [ 1  1  0]
 [ 0  1  1]
 [ 1  0  1]]
b = 
[-5  0  1 -2]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)