In [1]:
import numpy as np

In [4]:
# Definición del gridworld
gridworld = np.array([
    [-1, -1, -1, 1],
    [-1, -1, -1, -1],
    [-1, -1, -1, -1],
    [-1, -1, -1, -1]
])

In [11]:
# Parámetros de Q-Learning
alpha = 0.1
gamma = 0.9
num_episodes = 1000

In [12]:
# Definición de las acciones posibles: arriba, abajo, izquierda, derecha
acciones = [(0, -1), (0, 1), (-1, 0), (1, 0)]

In [13]:
# Implementación de Q-Learning

# Inicialización de Q
Q = np.zeros((gridworld.shape[0], gridworld.shape[1], len(acciones)))
for _ in range(num_episodes):
    estado = (0, 0)  # Estado inicial
    while estado != (0, 3):  # Asumamos que (0, 3) es el estado terminal
        accion = np.random.choice(range(len(acciones)))
        nueva_fila = estado[0] + acciones[accion][0]
        nueva_col = estado[1] + acciones[accion][1]

        # Asegúrate de que la nueva posición esté dentro del gridworld
        if 0 <= nueva_fila < gridworld.shape[0] and 0 <= nueva_col < gridworld.shape[1]:
            recompensa = gridworld[nueva_fila, nueva_col]
            nuevo_valor = recompensa + gamma * np.max(Q[nueva_fila, nueva_col])
            Q[estado[0], estado[1], accion] = (1 - alpha) * Q[estado[0], estado[1], accion] + alpha * nuevo_valor
            estado = (nueva_fila, nueva_col)


In [14]:
print("Q-values después del entrenamiento: ")
print(Q)

Q-values después del entrenamiento: 
[[[ 0.   -1.    0.   -1.  ]
  [-1.   -0.1   0.   -1.9 ]
  [-1.    1.    0.   -1.09]
  [ 0.    0.    0.    0.  ]]

 [[ 0.   -1.9  -1.   -1.  ]
  [-1.   -1.09 -1.   -1.9 ]
  [-1.9  -0.1  -0.1  -1.9 ]
  [-1.09  0.    1.   -1.  ]]

 [[ 0.   -1.9  -1.   -1.  ]
  [-1.   -1.9  -1.9  -1.  ]
  [-1.9  -1.   -1.09 -1.  ]
  [-1.9   0.   -0.1  -1.  ]]

 [[ 0.   -1.   -1.    0.  ]
  [-1.   -1.   -1.9   0.  ]
  [-1.   -1.   -1.9   0.  ]
  [-1.    0.   -1.    0.  ]]]


In [27]:
# Definición del entorno de navegación (datos ficticios)
entorno = np.array([
[0, 0, 0, 0, 0],
[0, -1, -1, -1, 0],
[0, 0, -1, 0, 0],
[0, -1, -1, -1, 0],
[0, 0, 0, 0, 0]
 ])

In [28]:
# Definición de acciones posibles (arriba, abajo, izquierda, derecha)
acciones = [(0, -1), (0, 1), (-1, 0), (1, 0)]

In [29]:
# Implementación de Q-Learning
Q = np.zeros((entorno.shape[0], entorno.shape[1], len (acciones)))
gamma = 0.9 # Factor de descuento
alpha = 8.1 #Tasa de aprendizaje
num_episodes = 1000

In [30]:
# Entrenamiento de Q-Learning
for _ in range(num_episodes):
    estado = (0, 0)  # Estado inicial
    while estado != (0, 3):  # Corrección aquí
        accion = np.random.choice(range(len(acciones)))
        nueva_fila = estado[0] + acciones[accion][0]
        nueva_col = estado[1] + acciones[accion][1]

        # Asegúrate de que la nueva posición esté dentro del gridworld
        if 0 <= nueva_fila < gridworld.shape[0] and 0 <= nueva_col < gridworld.shape[1]:
            recompensa = gridworld[nueva_fila, nueva_col]
            nuevo_valor = recompensa + gamma * np.max(Q[nueva_fila, nueva_col])
            Q[estado[0], estado[1], accion] = (1 - alpha) * Q[estado[0], estado[1], accion] + alpha * nuevo_valor
            estado = (nueva_fila, nueva_col)
            
            if recompensa == 1:  # Suponemos que el objetivo es llegar a la recompensa de 1
                break

C:\Users\deyvi.caicedo\AppData\Local\Temp\ipykernel_35292\2601618761.py:13: RuntimeWarning: overflow encountered in scalar multiply
  Q[estado[0], estado[1], accion] = (1 - alpha) * Q[estado[0], estado[1], accion] + alpha * nuevo_valor
C:\Users\deyvi.caicedo\AppData\Local\Temp\ipykernel_35292\2601618761.py:13: RuntimeWarning: invalid value encountered in scalar add
  Q[estado[0], estado[1], accion] = (1 - alpha) * Q[estado[0], estado[1], accion] + alpha * nuevo_valor


In [31]:
print("Valores Q después del entrenamiento:")
print(Q)

Valores Q después del entrenamiento:
[[[ 0. nan  0. nan]
  [nan nan  0. nan]
  [nan inf  0. nan]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0. nan nan nan]
  [nan nan nan nan]
  [nan nan nan nan]
  [nan  0. inf nan]
  [ 0.  0.  0.  0.]]

 [[ 0. nan nan nan]
  [nan nan nan nan]
  [nan nan nan nan]
  [nan  0. nan nan]
  [ 0.  0.  0.  0.]]

 [[ 0. nan nan  0.]
  [nan nan nan  0.]
  [nan nan nan  0.]
  [nan  0. nan  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]


In [33]:
# Definición de los estados (niveles de inventario), acciones (órdenes de reabastecimiento) y recompensas (costos, ganancias, etc.)
estados = ['Bajo', 'Medio', 'Alto']
acciones = ['Reabastecer', 'No reabastecer']

In [36]:
recompensas = {
        ('Bajo', 'Reabastecer'): 50, 
        ('Bajo', 'No reabastecer'): -10,
        ('Medio', 'Reabastecer'): 38,
        ('Medio', 'No reabastecer'): 0,
        ('Alto', 'Reabastecer'): 10,
        ('Alto', 'No reabastecer'): -20
 }

In [37]:
# Implementación de Q-Learning
Q = {}
gamma = 0.9 # Factor de descuento
alpha = 0.1 # Tasa de aprendizaje
num_episodes = 1000

In [41]:
for _ in range(num_episodes):
    estado_actual = np.random.choice(estados)
    while True:
        accion = np.random.choice(acciones)
        recompensa = recompensas.get((estado_actual, accion), 0)  # Manejo de casos donde (estado, accion) no está en recompensas

        # Inicializar Q para el estado y acción si no existe
        if estado_actual not in Q:
            Q[estado_actual] = {}
        if accion not in Q[estado_actual]:
            Q[estado_actual][accion] = 0

        nuevo_estado = np.random.choice(estados)

        # Obtener el máximo valor de Q para el nuevo estado
        if nuevo_estado in Q and Q[nuevo_estado]:
            max_nuevo_estado = max(Q[nuevo_estado].values())
        else:
            max_nuevo_estado = 0

        # Actualización de la tabla Q
        Q[estado_actual][accion] += alpha * (recompensa + gamma * max_nuevo_estado - Q[estado_actual][accion])

        estado_actual = nuevo_estado
        
        # Condición de terminación
        if recompensa in {50, 30, 10}:  # Usar conjunto para verificar múltiples valores
            break

In [42]:
print("Valores Q después del entrenamiento:")
print(Q)

Valores Q después del entrenamiento:
{'Alto': {'No reabastecer': 271.045912557071, 'Reabastecer': 307.0983461425744}, 'Bajo': {'No reabastecer': 289.37241507833494, 'Reabastecer': 342.7698327339255}, 'Medio': {'Reabastecer': 325.28939043045676, 'No reabastecer': 296.79031392564985}}
